// @author kongweiguang

//! HTML document generation for Markdown export.

use std::fs;
use std::path::Path;

use base64::{Engine as _, engine::general_purpose};
use gpui::{Hsla, Rgba};
use pulldown_cmark::{CowStr, Event, Options, Parser, Tag, html};

use crate::components::{
    HtmlImageBlock, MermaidThemeMode, collect_toc_entries, inline_math_font_size,
    is_mermaid_closing_fence, is_toc_marker, parse_display_math_source, parse_html_image_block,
    parse_image_reference_definitions, parse_mermaid_fence_source, parse_mermaid_fence_start,
    parse_standalone_image, render_latex_to_svg, render_mermaid_to_svg, sanitize_html_for_export,
};
use crate::net;
use crate::theme::{FontWeightDef, Theme};

/// Builds a full HTML document with embedded CSS derived from the active theme.
#[cfg(test)]
pub(crate) fn render_html(markdown: &str, theme: &Theme, title: &str) -> String {
    render_html_with_base_dir(markdown, theme, title, None)
}

/// Builds export HTML and resolves local Markdown image paths relative to the source document.
pub(crate) fn render_html_with_base_dir(
    markdown: &str,
    theme: &Theme,
    title: &str,
    base_dir: Option<&Path>,
) -> String {
    render_html_document(markdown, theme, title, base_dir, &theme_css(theme))
}

/// Builds HTML tailored for Chromium's print-to-PDF pipeline.
pub(crate) fn render_chromium_pdf_html_with_base_dir(
    markdown: &str,
    theme: &Theme,
    title: &str,
    base_dir: Option<&Path>,
) -> String {
    render_html_document(
        markdown,
        theme,
        title,
        base_dir,
        &chromium_pdf_theme_css(theme),
    )
}

fn render_html_document(
    markdown: &str,
    theme: &Theme,
    title: &str,
    base_dir: Option<&Path>,
    css: &str,
) -> String {
    let document_lang = if contains_tibetan_text(markdown) || contains_tibetan_text(title) {
        "bo"
    } else {
        "en"
    };
    let body = render_browser_html_body(markdown, theme, base_dir);

    format!(
        "<!doctype html>\n<html lang=\"{}\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>{}</title>\n<style>\n{}\n</style>\n</head>\n<body>\n<main class=\"vlt-document\">\n{}</main>\n</body>\n</html>\n",
        document_lang,
        escape_html(title),
        css,
        body,
    )
}

fn markdown_options() -> Options {
    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_FOOTNOTES);
    options.insert(Options::ENABLE_TASKLISTS);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_GFM);
    options
}

fn render_browser_html_body(markdown: &str, theme: &Theme, base_dir: Option<&Path>) -> String {
    let rewritten = rewrite_scaled_standalone_images(markdown);
    let rewritten = rewrite_visible_comment_blocks(&rewritten);
    let rewritten = rewrite_unsafe_html_blocks(&rewritten, base_dir);
    let rewritten = rewrite_display_math_blocks(&rewritten, theme);
    let rewritten = rewrite_inline_math(&rewritten, theme);
    let rewritten = rewrite_mermaid_blocks(&rewritten, theme);
    // This projection is generated by gmark after user HTML sanitization. Its anchors are derived
    // from source headings and escaped below, so it must not be downgraded as untrusted HTML.
    let rewritten = rewrite_table_of_contents_markers(&rewritten);
    let parser = Parser::new_ext(&rewritten, markdown_options())
        .map(|event| rewrite_local_image_event(event, base_dir));
    let mut body = String::new();
    html::push_html(&mut body, parser);
    inject_heading_ids(&body, &collect_toc_entries(markdown))
}

/// Replaces only standalone source markers. Fenced code remains literal so snippets can document
/// `[TOC]` without unexpectedly emitting navigation.
fn rewrite_table_of_contents_markers(markdown: &str) -> String {
    let entries = collect_toc_entries(markdown);
    let mut rewritten = Vec::new();
    let mut active_fence: Option<(char, usize)> = None;
    for line in markdown.split('\n') {
        if let Some((marker, run_len)) = active_fence {
            rewritten.push(line.to_owned());
            if is_closing_fence(line, marker, run_len) {
                active_fence = None;
            }
            continue;
        }
        if let Some(fence) = opening_fence(line) {
            active_fence = Some(fence);
            rewritten.push(line.to_owned());
            continue;
        }
        if is_toc_marker(line) {
            rewritten.push(render_table_of_contents_html(&entries));
        } else {
            rewritten.push(line.to_owned());
        }
    }
    rewritten.join("\n")
}

fn render_table_of_contents_html(entries: &[crate::components::TocEntry]) -> String {
    let mut html = String::from("<nav class=\"gmark-toc\" aria-label=\"Table of contents\"><ol>");
    for entry in entries {
        html.push_str(&format!(
            "<li class=\"gmark-toc-level-{}\"><a href=\"#{}\">{}</a></li>",
            entry.level,
            escape_html(&entry.slug),
            escape_html(&entry.title),
        ));
    }
    html.push_str("</ol></nav>");
    html
}

fn inject_heading_ids(body: &str, entries: &[crate::components::TocEntry]) -> String {
    let mut rewritten = body.to_string();
    let mut search_from = 0;
    for entry in entries {
        let open = format!("<h{}>", entry.level);
        let Some(offset) = rewritten[search_from..].find(&open) else {
            continue;
        };
        let offset = search_from + offset;
        let replacement = format!("<h{} id=\"{}\">", entry.level, escape_html(&entry.slug));
        rewritten.replace_range(offset..offset + open.len(), &replacement);
        search_from = offset + replacement.len();
    }
    rewritten
}

fn rewrite_scaled_standalone_images(markdown: &str) -> String {
    let definitions = parse_image_reference_definitions(markdown);
    let mut rewritten = Vec::new();
    let mut active_fence: Option<(char, usize)> = None;
    for line in markdown.split('\n') {
        if let Some((marker, run_len)) = active_fence {
            rewritten.push(line.to_owned());
            if is_closing_fence(line, marker, run_len) {
                active_fence = None;
            }
            continue;
        }
        if let Some(fence) = opening_fence(line) {
            active_fence = Some(fence);
            rewritten.push(line.to_owned());
            continue;
        }
        let Some(syntax) = parse_standalone_image(line) else {
            rewritten.push(line.to_owned());
            continue;
        };
        if syntax.width_percent == 100 {
            rewritten.push(line.to_owned());
            continue;
        }
        let Some(target) = syntax.resolve_target(&definitions) else {
            rewritten.push(line.to_owned());
            continue;
        };
        let indent = &line[..line.len() - line.trim_start().len()];
        let image = HtmlImageBlock {
            src: target.src,
            alt: syntax.alt,
            title: target.title,
            zoom: 1.0,
            width_percent: Some(syntax.width_percent),
        };
        rewritten.push(format!(
            "{indent}{}",
            image.to_sanitized_html_with_src(&image.src)
        ));
    }
    rewritten.join("\n")
}

fn rewrite_visible_comment_blocks(markdown: &str) -> String {
    let lines = markdown.split('\n').collect::<Vec<_>>();
    let mut rewritten = Vec::with_capacity(lines.len());
    let mut index = 0usize;
    let mut active_fence: Option<(char, usize)> = None;

    while index < lines.len() {
        let line = lines[index];
        if let Some((marker, run_len)) = active_fence {
            rewritten.push(line.to_string());
            if is_closing_fence(line, marker, run_len) {
                active_fence = None;
            }
            index += 1;
            continue;
        }

        if let Some(fence) = opening_fence(line) {
            active_fence = Some(fence);
            rewritten.push(line.to_string());
            index += 1;
            continue;
        }

        if !is_root_comment_start(line) {
            rewritten.push(line.to_string());
            index += 1;
            continue;
        }

        let start = index;
        let mut end = index;
        while end < lines.len() && !lines[end].contains("-->") {
            end += 1;
        }

        if end >= lines.len() {
            rewritten.push(line.to_string());
            index += 1;
            continue;
        }

        let raw_comment = lines[start..=end].join("\n");
        rewritten.push(format!(
            "<pre class=\"vlt-comment\">{}</pre>",
            escape_html(&raw_comment)
        ));
        index = end + 1;
    }

    rewritten.join("\n")
}

fn rewrite_inline_math(markdown: &str, theme: &Theme) -> String {
    let mut rewritten = Vec::new();
    let mut active_fence: Option<(char, usize)> = None;
    for line in markdown.split('\n') {
        if let Some((marker, run_len)) = active_fence {
            rewritten.push(line.to_string());
            if is_closing_fence(line, marker, run_len) {
                active_fence = None;
            }
            continue;
        }

        if let Some(fence) = opening_fence(line) {
            active_fence = Some(fence);
            rewritten.push(line.to_string());
            continue;
        }

        rewritten.push(rewrite_inline_math_line(line, theme));
    }

    rewritten.join("\n")
}

fn rewrite_inline_math_line(line: &str, theme: &Theme) -> String {
    let mut output = String::with_capacity(line.len());
    let mut index = 0usize;
    while index < line.len() {
        if line[index..].starts_with('`') {
            let run_len = line[index..]
                .bytes()
                .take_while(|byte| *byte == b'`')
                .count();
            if let Some(close) = find_backtick_run(line, index + run_len, run_len) {
                output.push_str(&line[index..close + run_len]);
                index = close + run_len;
                continue;
            }
        }

        if let Some((end, body)) = locate_inline_dollar_math_source(line, index)
            .or_else(|| locate_inline_paren_math_source(line, index))
        {
            match render_latex_to_svg(
                &body,
                theme.colors.text_default,
                inline_math_font_size(theme.typography.text_size),
            ) {
                Ok(svg) => {
                    output.push_str(&format!("<span class=\"vlt-inline-math\">{svg}</span>"))
                }
                Err(_) => output.push_str(&escape_html(&line[index..end])),
            }
            index = end;
            continue;
        }

        if let Some((end, body, tag)) = locate_inline_script_source(line, index) {
            output.push_str(&format!("<{tag}>{}</{tag}>", escape_html(&body)));
            index = end;
            continue;
        }

        let Some(ch) = line[index..].chars().next() else {
            break;
        };
        output.push(ch);
        index += ch.len_utf8();
    }
    output
}

fn find_backtick_run(line: &str, mut index: usize, run_len: usize) -> Option<usize> {
    while index < line.len() {
        if line[index..].starts_with(&"`".repeat(run_len)) {
            return Some(index);
        }
        index += line[index..].chars().next()?.len_utf8();
    }
    None
}

fn locate_inline_dollar_math_source(line: &str, index: usize) -> Option<(usize, String)> {
    if !line[index..].starts_with('$')
        || line[index..].starts_with("$$")
        || is_escaped_ascii(line, index)
    {
        return None;
    }
    let mut cursor = index + 1;
    while cursor < line.len() {
        if line[cursor..].starts_with('$')
            && !line[cursor..].starts_with("$$")
            && !is_escaped_ascii(line, cursor)
        {
            let body = &line[index + 1..cursor];
            if valid_inline_math_body(body)
                && !looks_like_export_currency(line, index, cursor, body)
            {
                return Some((cursor + 1, body.to_string()));
            }
            return None;
        }
        cursor += line[cursor..].chars().next()?.len_utf8();
    }
    None
}

fn locate_inline_script_source(line: &str, index: usize) -> Option<(usize, String, &'static str)> {
    if is_escaped_ascii(line, index) {
        return None;
    }

    if line[index..].starts_with('^') {
        locate_script_close(line, index, '^').map(|(end, body)| (end, body, "sup"))
    } else if is_single_tilde_marker(line, index) {
        locate_script_close(line, index, '~').map(|(end, body)| (end, body, "sub"))
    } else {
        None
    }
}

fn locate_script_close(line: &str, index: usize, marker: char) -> Option<(usize, String)> {
    let prev = previous_char(line, index)?;
    if !prev.is_ascii_alphanumeric() {
        return None;
    }

    let body_start = index + marker.len_utf8();
    let first = line[body_start..].chars().next()?;
    if !first.is_ascii_alphanumeric() {
        return None;
    }

    let mut cursor = body_start;
    while cursor < line.len() {
        if line[cursor..].starts_with(marker)
            && !is_escaped_ascii(line, cursor)
            && (marker != '~' || is_single_tilde_marker(line, cursor))
        {
            let body = &line[body_start..cursor];
            return body
                .chars()
                .all(|ch| ch.is_ascii_alphanumeric())
                .then(|| (cursor + marker.len_utf8(), body.to_string()));
        }
        cursor += line[cursor..].chars().next()?.len_utf8();
    }

    None
}

fn previous_char(line: &str, index: usize) -> Option<char> {
    line.get(..index)?.chars().next_back()
}

fn is_single_tilde_marker(line: &str, index: usize) -> bool {
    line[index..].starts_with('~')
        && previous_char(line, index).is_none_or(|ch| ch != '~')
        && line[index + 1..].chars().next().is_none_or(|ch| ch != '~')
}

fn locate_inline_paren_math_source(line: &str, index: usize) -> Option<(usize, String)> {
    if !line[index..].starts_with("\\(") {
        return None;
    }
    let mut cursor = index + 2;
    while cursor + 1 < line.len() {
        if line[cursor..].starts_with("\\)") {
            let body = &line[index + 2..cursor];
            if valid_inline_math_body(body) {
                return Some((cursor + 2, body.to_string()));
            }
            return None;
        }
        cursor += line[cursor..].chars().next()?.len_utf8();
    }
    None
}

fn valid_inline_math_body(body: &str) -> bool {
    !body.is_empty() && !body.contains(['\n', '\r']) && body.trim() == body && !body.is_empty()
}

fn is_escaped_ascii(line: &str, index: usize) -> bool {
    let mut slash_count = 0usize;
    let mut cursor = index;
    while cursor > 0 && line.as_bytes()[cursor - 1] == b'\\' {
        slash_count += 1;
        cursor -= 1;
    }
    slash_count % 2 == 1
}
#[path = "html_parts/preprocess.rs"]
mod preprocess;
use preprocess::{
    chromium_pdf_theme_css, contains_tibetan_text, escape_html, is_closing_fence,
    is_root_comment_start, looks_like_export_currency, opening_fence, rewrite_display_math_blocks,
    rewrite_local_image_event, rewrite_mermaid_blocks, rewrite_unsafe_html_blocks, theme_css,
};
#[cfg(test)]
#[path = "../../tests/unit/export/html.rs"]
mod tests;
