// @author kongweiguang

use super::*;

/// Deserialization adapter for `ThemeDimensions` with backward-compatible defaults.
#[derive(Deserialize)]
struct ThemeDimensionsDe {
    editor_padding: f32,
    block_gap: f32,
    block_min_height: f32,
    block_padding_y: f32,
    block_padding_x: f32,
    nested_block_indent: f32,
    list_marker_gap: f32,
    list_marker_width: f32,
    ordered_list_marker_width: f32,
    task_checkbox_size: Option<f32>,
    task_checkbox_radius: Option<f32>,
    task_checkbox_border_width: Option<f32>,
    task_checkbox_check_size: Option<f32>,
    h1_padding_bottom: f32,
    h1_margin_bottom: f32,
    cursor_width: f32,
    underline_thickness: f32,
    h1_border_width: f32,
    quote_border_width: f32,
    quote_padding_left: f32,
    callout_padding_x: Option<f32>,
    callout_padding_y: Option<f32>,
    callout_body_gap: Option<f32>,
    callout_radius: Option<f32>,
    callout_border_width: Option<f32>,
    callout_header_gap: Option<f32>,
    callout_header_margin_bottom: Option<f32>,
    footnote_padding_x: Option<f32>,
    footnote_padding_y: Option<f32>,
    footnote_radius: Option<f32>,
    footnote_badge_padding_x: Option<f32>,
    footnote_badge_padding_y: Option<f32>,
    separator_thickness: Option<f32>,
    separator_inset_x: Option<f32>,
    separator_margin_y: Option<f32>,
    code_block_padding_y: f32,
    code_block_padding_x: f32,
    code_bg_pad_x: f32,
    code_bg_pad_y: f32,
    code_bg_radius: f32,
    code_language_input_width: Option<f32>,
    code_language_input_height: Option<f32>,
    code_language_input_padding_x: Option<f32>,
    code_language_input_padding_y: Option<f32>,
    code_language_input_radius: Option<f32>,
    code_language_input_border_width: Option<f32>,
    code_language_input_gap: Option<f32>,
    table_cell_padding_x: Option<f32>,
    table_cell_padding_y: Option<f32>,
    table_cell_min_height: Option<f32>,
    table_append_button_extent: Option<f32>,
    table_append_button_inset: Option<f32>,
    table_append_activation_band: Option<f32>,
    image_radius: Option<f32>,
    image_root_max_height: Option<f32>,
    image_cell_max_height: Option<f32>,
    image_root_placeholder_height: Option<f32>,
    image_cell_placeholder_height: Option<f32>,
    image_caption_gap: Option<f32>,
    scrollbar_width: f32,
    scrollbar_right: f32,
    centered_shrink_start: f32,
    centered_shrink_end: f32,
    centered_min_ratio: f32,
    centered_max_width: Option<f32>,
    dialog_width: f32,
    dialog_padding: f32,
    dialog_gap: f32,
    dialog_radius: f32,
    dialog_border_width: f32,
    dialog_button_height: f32,
    dialog_button_gap: f32,
    dialog_button_padding_x: f32,
    menu_bar_height: Option<f32>,
    menu_bar_padding_x: Option<f32>,
    menu_bar_padding_y: Option<f32>,
    menu_bar_gap: Option<f32>,
    menu_bar_button_width: Option<f32>,
    menu_bar_button_height: Option<f32>,
    menu_bar_button_padding_x: Option<f32>,
    menu_bar_button_radius: Option<f32>,
    menu_text_size: Option<f32>,
    menu_panel_top: Option<f32>,
    menu_panel_width: Option<f32>,
    menu_panel_padding: Option<f32>,
    menu_panel_gap: Option<f32>,
    menu_panel_radius: Option<f32>,
    menu_item_height: Option<f32>,
    menu_item_padding_x: Option<f32>,
    menu_item_radius: Option<f32>,
    menu_separator_margin_x: Option<f32>,
    menu_separator_margin_y: Option<f32>,
    menu_separator_height: Option<f32>,
    context_menu_panel_width: Option<f32>,
    context_menu_submenu_width: Option<f32>,
    context_menu_submenu_gap: Option<f32>,
    context_menu_axis_panel_width: Option<f32>,
    table_insert_dialog_width: Option<f32>,
    table_insert_stepper_gap: Option<f32>,
    table_insert_stepper_button_size: Option<f32>,
    table_insert_stepper_value_min_width: Option<f32>,
    table_insert_stepper_value_padding_x: Option<f32>,
    table_insert_stepper_radius: Option<f32>,
    view_mode_toggle_left: Option<f32>,
    view_mode_toggle_bottom: Option<f32>,
    view_mode_toggle_padding_x: Option<f32>,
    view_mode_toggle_padding_y: Option<f32>,
    view_mode_toggle_min_width: Option<f32>,
    view_mode_toggle_radius: Option<f32>,
    view_mode_toggle_border_width: Option<f32>,
    view_mode_toggle_text_size: Option<f32>,
    status_bar_height: Option<f32>,
    status_bar_padding_x: Option<f32>,
    status_bar_item_gap: Option<f32>,
    status_bar_text_size: Option<f32>,
}

impl<'de> Deserialize<'de> for ThemeDimensions {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let raw = ThemeDimensionsDe::deserialize(deserializer)?;
        Ok(Self {
            editor_padding: raw.editor_padding,
            block_gap: raw.block_gap,
            block_min_height: raw.block_min_height,
            block_padding_y: raw.block_padding_y,
            block_padding_x: raw.block_padding_x,
            nested_block_indent: raw.nested_block_indent,
            list_marker_gap: raw.list_marker_gap,
            list_marker_width: raw.list_marker_width,
            ordered_list_marker_width: raw.ordered_list_marker_width,
            task_checkbox_size: raw.task_checkbox_size.unwrap_or(14.0),
            task_checkbox_radius: raw.task_checkbox_radius.unwrap_or(4.0),
            task_checkbox_border_width: raw.task_checkbox_border_width.unwrap_or(1.0),
            task_checkbox_check_size: raw.task_checkbox_check_size.unwrap_or(10.0),
            h1_padding_bottom: raw.h1_padding_bottom,
            h1_margin_bottom: raw.h1_margin_bottom,
            cursor_width: raw.cursor_width,
            underline_thickness: raw.underline_thickness,
            h1_border_width: raw.h1_border_width,
            quote_border_width: raw.quote_border_width,
            quote_padding_left: raw.quote_padding_left,
            callout_padding_x: raw.callout_padding_x.unwrap_or(14.0),
            callout_padding_y: raw.callout_padding_y.unwrap_or(10.0),
            callout_body_gap: raw.callout_body_gap.unwrap_or(8.0),
            callout_radius: raw.callout_radius.unwrap_or(10.0),
            callout_border_width: raw.callout_border_width.unwrap_or(4.0),
            callout_header_gap: raw.callout_header_gap.unwrap_or(6.0),
            callout_header_margin_bottom: raw.callout_header_margin_bottom.unwrap_or(6.0),
            footnote_padding_x: raw.footnote_padding_x.unwrap_or(10.0),
            footnote_padding_y: raw.footnote_padding_y.unwrap_or(6.0),
            footnote_radius: raw.footnote_radius.unwrap_or(6.0),
            footnote_badge_padding_x: raw.footnote_badge_padding_x.unwrap_or(4.0),
            footnote_badge_padding_y: raw.footnote_badge_padding_y.unwrap_or(1.0),
            separator_thickness: raw.separator_thickness.unwrap_or(1.0),
            separator_inset_x: raw.separator_inset_x.unwrap_or(40.0),
            separator_margin_y: raw.separator_margin_y.unwrap_or(10.0),
            code_block_padding_y: raw.code_block_padding_y,
            code_block_padding_x: raw.code_block_padding_x,
            code_bg_pad_x: raw.code_bg_pad_x,
            code_bg_pad_y: raw.code_bg_pad_y,
            code_bg_radius: raw.code_bg_radius,
            code_language_input_width: raw.code_language_input_width.unwrap_or(156.0),
            code_language_input_height: raw.code_language_input_height.unwrap_or(18.0),
            code_language_input_padding_x: raw.code_language_input_padding_x.unwrap_or(8.0),
            code_language_input_padding_y: raw.code_language_input_padding_y.unwrap_or(3.0),
            code_language_input_radius: raw.code_language_input_radius.unwrap_or(6.0),
            code_language_input_border_width: raw.code_language_input_border_width.unwrap_or(1.0),
            code_language_input_gap: raw.code_language_input_gap.unwrap_or(8.0),
            table_cell_padding_x: raw.table_cell_padding_x.unwrap_or(10.0),
            table_cell_padding_y: raw.table_cell_padding_y.unwrap_or(8.0),
            table_cell_min_height: raw.table_cell_min_height.unwrap_or(42.0),
            table_append_button_extent: raw.table_append_button_extent.unwrap_or(16.0),
            table_append_button_inset: raw.table_append_button_inset.unwrap_or(8.0),
            table_append_activation_band: raw.table_append_activation_band.unwrap_or(18.0),
            image_radius: raw.image_radius.unwrap_or(12.0),
            image_root_max_height: raw.image_root_max_height.unwrap_or(420.0),
            image_cell_max_height: raw.image_cell_max_height.unwrap_or(180.0),
            image_root_placeholder_height: raw.image_root_placeholder_height.unwrap_or(260.0),
            image_cell_placeholder_height: raw.image_cell_placeholder_height.unwrap_or(120.0),
            image_caption_gap: raw.image_caption_gap.unwrap_or(8.0),
            scrollbar_width: raw.scrollbar_width,
            scrollbar_right: raw.scrollbar_right,
            centered_shrink_start: raw.centered_shrink_start,
            centered_shrink_end: raw.centered_shrink_end,
            centered_min_ratio: raw.centered_min_ratio,
            centered_max_width: raw.centered_max_width.unwrap_or(1200.0),
            dialog_width: raw.dialog_width,
            dialog_padding: raw.dialog_padding,
            dialog_gap: raw.dialog_gap,
            dialog_radius: raw.dialog_radius,
            dialog_border_width: raw.dialog_border_width,
            dialog_button_height: raw.dialog_button_height,
            dialog_button_gap: raw.dialog_button_gap,
            dialog_button_padding_x: raw.dialog_button_padding_x,
            menu_bar_height: raw.menu_bar_height.unwrap_or(32.0),
            menu_bar_padding_x: raw.menu_bar_padding_x.unwrap_or(10.0),
            menu_bar_padding_y: raw.menu_bar_padding_y.unwrap_or(4.0),
            menu_bar_gap: raw.menu_bar_gap.unwrap_or(2.0),
            menu_bar_button_width: raw.menu_bar_button_width.unwrap_or(48.0),
            menu_bar_button_height: raw.menu_bar_button_height.unwrap_or(24.0),
            menu_bar_button_padding_x: raw.menu_bar_button_padding_x.unwrap_or(8.0),
            menu_bar_button_radius: raw.menu_bar_button_radius.unwrap_or(5.0),
            menu_text_size: raw.menu_text_size.unwrap_or(12.0),
            menu_panel_top: raw.menu_panel_top.unwrap_or(30.0),
            menu_panel_width: raw.menu_panel_width.unwrap_or(180.0),
            menu_panel_padding: raw.menu_panel_padding.unwrap_or(4.0),
            menu_panel_gap: raw.menu_panel_gap.unwrap_or(1.0),
            menu_panel_radius: raw.menu_panel_radius.unwrap_or(10.0),
            menu_item_height: raw.menu_item_height.unwrap_or(28.0),
            menu_item_padding_x: raw.menu_item_padding_x.unwrap_or(8.0),
            menu_item_radius: raw.menu_item_radius.unwrap_or(7.0),
            menu_separator_margin_x: raw.menu_separator_margin_x.unwrap_or(6.0),
            menu_separator_margin_y: raw.menu_separator_margin_y.unwrap_or(3.0),
            menu_separator_height: raw.menu_separator_height.unwrap_or(1.0),
            context_menu_panel_width: raw.context_menu_panel_width.unwrap_or(132.0),
            context_menu_submenu_width: raw.context_menu_submenu_width.unwrap_or(148.0),
            context_menu_submenu_gap: raw.context_menu_submenu_gap.unwrap_or(2.0),
            context_menu_axis_panel_width: raw.context_menu_axis_panel_width.unwrap_or(164.0),
            table_insert_dialog_width: raw.table_insert_dialog_width.unwrap_or(380.0),
            table_insert_stepper_gap: raw.table_insert_stepper_gap.unwrap_or(8.0),
            table_insert_stepper_button_size: raw.table_insert_stepper_button_size.unwrap_or(32.0),
            table_insert_stepper_value_min_width: raw
                .table_insert_stepper_value_min_width
                .unwrap_or(56.0),
            table_insert_stepper_value_padding_x: raw
                .table_insert_stepper_value_padding_x
                .unwrap_or(10.0),
            table_insert_stepper_radius: raw.table_insert_stepper_radius.unwrap_or(8.0),
            view_mode_toggle_left: raw.view_mode_toggle_left.unwrap_or(12.0),
            view_mode_toggle_bottom: raw.view_mode_toggle_bottom.unwrap_or(12.0),
            view_mode_toggle_padding_x: raw.view_mode_toggle_padding_x.unwrap_or(8.0),
            view_mode_toggle_padding_y: raw.view_mode_toggle_padding_y.unwrap_or(4.0),
            view_mode_toggle_min_width: raw.view_mode_toggle_min_width.unwrap_or(88.0),
            view_mode_toggle_radius: raw.view_mode_toggle_radius.unwrap_or(999.0),
            view_mode_toggle_border_width: raw.view_mode_toggle_border_width.unwrap_or(1.0),
            view_mode_toggle_text_size: raw.view_mode_toggle_text_size.unwrap_or(11.0),
            status_bar_height: raw.status_bar_height.unwrap_or(24.0),
            status_bar_padding_x: raw.status_bar_padding_x.unwrap_or(12.0),
            status_bar_item_gap: raw.status_bar_item_gap.unwrap_or(12.0),
            status_bar_text_size: raw.status_bar_text_size.unwrap_or(11.0),
        })
    }
}

/// Top-level theme combining colors, dimensions, typography and placeholders.
///
/// Can be deserialized from JSON, allowing users to ship custom theme files.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Theme {
    pub name: String,
    pub colors: ThemeColors,
    pub dimensions: ThemeDimensions,
    pub typography: ThemeTypography,
    pub placeholders: Placeholders,
}

impl Theme {
    /// Returns the built-in fallback theme used when no custom theme is loaded.
    pub fn default_theme() -> Self {
        Self {
            name: "gmark".into(),
            colors: ThemeColors {
                editor_background: Hsla::from(rgba(0x191919ff)),
                source_mode_block_bg: Hsla::from(rgba(0x313131ff)),
                comment_bg: Hsla::from(rgba(0xfbbf2426)),
                text_default: Hsla::from(rgba(0xf0efedff)),
                text_link: Hsla::from(rgba(0x60a5faff)),
                text_placeholder: hsla(0., 0., 0.6, 1.0),
                text_h1: Hsla::from(rgba(0xf0efedff)),
                text_h2: Hsla::from(rgba(0xf0efedff)),
                text_h3: Hsla::from(rgba(0xf0efedff)),
                text_h4: Hsla::from(rgba(0xf0efedff)),
                text_h5: Hsla::from(rgba(0xf0efedff)),
                text_h6: Hsla::from(rgba(0xf0efedff)),
                border_h1: Hsla::from(rgba(0xe0e0e0ff)),
                border_h2: Hsla::from(rgba(0xe0e0e0cc)),
                text_quote: Hsla::from(rgba(0xd1d5dbff)),
                border_quote: Hsla::from(rgba(0x6b7280ff)),
                callout_note_bg: Hsla::from(rgba(0x94a3b81f)),
                callout_note_border: Hsla::from(rgba(0x94a3b4ff)),
                callout_tip_bg: Hsla::from(rgba(0x1d4ed81f)),
                callout_tip_border: Hsla::from(rgba(0x60a5faff)),
                callout_important_bg: Hsla::from(rgba(0xa78bfa1f)),
                callout_important_border: Hsla::from(rgba(0xa78bfaff)),
                callout_warning_bg: Hsla::from(rgba(0xfb71851f)),
                callout_warning_border: Hsla::from(rgba(0xfb7185ff)),
                callout_caution_bg: Hsla::from(rgba(0xdc26261f)),
                callout_caution_border: Hsla::from(rgba(0xf87171ff)),
                footnote_bg: Hsla::from(rgba(0x212124ff)),
                footnote_border: Hsla::from(rgba(0x71717a52)),
                footnote_badge_bg: Hsla::from(rgba(0xa1a1aa24)),
                footnote_badge_text: Hsla::from(rgba(0xd4d4d8cc)),
                footnote_backref: Hsla::from(rgba(0xa1a1aaff)),
                task_checkbox_border: Hsla::from(rgba(0x71717aff)),
                task_checkbox_bg: Hsla::from(rgba(0x00000000)),
                task_checkbox_checked_bg: Hsla::from(rgba(0xf0efedff)),
                task_checkbox_check: Hsla::from(rgba(0x18181bff)),
                separator_color: Hsla::from(rgba(0x71717aff)),
                code_bg: Hsla::from(rgba(0x23272eff)),
                code_text: Hsla::from(rgba(0xe5e7ebff)),
                code_language_input_bg: Hsla::from(rgba(0x343941ff)),
                code_language_input_border: Hsla::from(rgba(0x4b5563cc)),
                code_language_input_text: Hsla::from(rgba(0xe5e7ebff)),
                code_language_input_placeholder: Hsla::from(rgba(0x9ca3afcc)),
                code_syntax_comment: Hsla::from(rgba(0x565f89ff)),
                code_syntax_keyword: Hsla::from(rgba(0xbb9af7ff)),
                code_syntax_string: Hsla::from(rgba(0x9ece6aff)),
                code_syntax_number: Hsla::from(rgba(0xff9e64ff)),
                code_syntax_type: Hsla::from(rgba(0x2ac3deff)),
                code_syntax_function: Hsla::from(rgba(0x7aa2f7ff)),
                code_syntax_constant: Hsla::from(rgba(0xffd166ff)),
                code_syntax_variable: Hsla::from(rgba(0xe5e9f0ff)),
                code_syntax_property: Hsla::from(rgba(0x7dcfffcc)),
                code_syntax_operator: Hsla::from(rgba(0x89ddffff)),
                code_syntax_punctuation: Hsla::from(rgba(0x9aa5ceff)),
                table_border: Hsla::from(rgba(0x3f3f46ff)),
                table_header_bg: Hsla::from(rgba(0x232326ff)),
                table_cell_bg: Hsla::from(rgba(0x1d1d20ff)),
                table_cell_active_outline: Hsla::from(rgba(0x60a5faff)),
                table_axis_preview_bg: Hsla::from(rgba(0xf4f4f51a)),
                table_axis_selected_bg: Hsla::from(rgba(0xf4f4f533)),
                table_append_button_bg: Hsla::from(rgba(0x27272aff)),
                table_append_button_hover: Hsla::from(rgba(0x3f3f46ff)),
                table_append_button_text: Hsla::from(rgba(0xf4f4f5ff)),
                image_placeholder_bg: Hsla::from(rgba(0x202024ff)),
                image_placeholder_border: Hsla::from(rgba(0x52525bff)),
                image_placeholder_text: Hsla::from(rgba(0xd4d4d8ff)),
                image_caption_text: Hsla::from(rgba(0xa1a1aaff)),
                scrollbar_thumb: Hsla::from(rgba(0xd1d5dbd8)),
                cursor: Hsla::from(rgba(0xf0efedff)),
                selection: Hsla::from(rgba(0x1c3651ff)),
                dialog_backdrop: Hsla::from(rgba(0x09090bcc)),
                dialog_surface: Hsla::from(rgba(0x18181bff)),
                dialog_border: Hsla::from(rgba(0x27272aff)),
                dialog_title: Hsla::from(rgba(0xf4f4f5ff)),
                dialog_body: Hsla::from(rgba(0xd4d4d8ff)),
                dialog_muted: Hsla::from(rgba(0xa1a1aaff)),
                dialog_primary_button_bg: Hsla::from(rgba(0x0a84ffff)),
                dialog_primary_button_hover: Hsla::from(rgba(0x0077e6ff)),
                dialog_primary_button_text: Hsla::from(rgba(0xffffffff)),
                dialog_secondary_button_bg: Hsla::from(rgba(0x27272aff)),
                dialog_secondary_button_hover: Hsla::from(rgba(0x3f3f46ff)),
                dialog_secondary_button_text: Hsla::from(rgba(0xf4f4f5ff)),
                // Doubles as the destructive menu-item text color (e.g. Delete
                // Row/Column), so it must stay legible on the dark menu surface
                // rather than the muted red used previously.
                dialog_danger_button_bg: Hsla::from(rgba(0xef4444ff)),
                dialog_danger_button_hover: Hsla::from(rgba(0xdc2626ff)),
                dialog_danger_button_text: Hsla::from(rgba(0xfef2f2ff)),
                status_bar_background: Hsla::from(rgba(0x1c1c1fff)),
                status_bar_text: Hsla::from(rgba(0xd4d4d8cc)),
                status_bar_text_dim: Hsla::from(rgba(0x71717aff)),
                status_bar_button_hover: Hsla::from(rgba(0x3f3f46ff)),
                chrome_background: Hsla::from(rgba(0x1f1f21ff)),
                chrome_hover: Hsla::from(rgba(0x303034ff)),
                sidebar_background: Hsla::from(rgba(0x202022ff)),
                tab_strip_background: Hsla::from(rgba(0x202022ff)),
                tab_active_background: Hsla::from(rgba(0x191919ff)),
            },
            dimensions: ThemeDimensions {
                editor_padding: 24.0,
                block_gap: 6.0,
                block_min_height: 28.0,
                block_padding_y: 4.0,
                block_padding_x: 12.0,
                nested_block_indent: 20.0,
                list_marker_gap: 8.0,
                list_marker_width: 12.0,
                ordered_list_marker_width: 20.0,
                task_checkbox_size: 14.0,
                task_checkbox_radius: 4.0,
                task_checkbox_border_width: 1.0,
                task_checkbox_check_size: 10.0,
                h1_padding_bottom: 4.0,
                h1_margin_bottom: 4.0,
                cursor_width: 2.0,
                underline_thickness: 1.0,
                h1_border_width: 1.0,
                quote_border_width: 3.0,
                quote_padding_left: 12.0,
                callout_padding_x: 14.0,
                callout_padding_y: 10.0,
                callout_body_gap: 8.0,
                callout_radius: 10.0,
                callout_border_width: 4.0,
                callout_header_gap: 6.0,
                callout_header_margin_bottom: 6.0,
                footnote_padding_x: 10.0,
                footnote_padding_y: 6.0,
                footnote_radius: 6.0,
                footnote_badge_padding_x: 4.0,
                footnote_badge_padding_y: 1.0,
                separator_thickness: 1.0,
                separator_inset_x: 40.0,
                separator_margin_y: 10.0,
                code_block_padding_y: 8.0,
                code_block_padding_x: 12.0,
                code_bg_pad_x: 3.0,
                code_bg_pad_y: 1.0,
                code_bg_radius: 4.0,
                code_language_input_width: 156.0,
                code_language_input_height: 18.0,
                code_language_input_padding_x: 8.0,
                code_language_input_padding_y: 3.0,
                code_language_input_radius: 6.0,
                code_language_input_border_width: 1.0,
                code_language_input_gap: 8.0,
                table_cell_padding_x: 10.0,
                table_cell_padding_y: 8.0,
                table_cell_min_height: 42.0,
                table_append_button_extent: 16.0,
                table_append_button_inset: 8.0,
                table_append_activation_band: 18.0,
                image_radius: 12.0,
                image_root_max_height: 420.0,
                image_cell_max_height: 180.0,
                image_root_placeholder_height: 260.0,
                image_cell_placeholder_height: 120.0,
                image_caption_gap: 8.0,
                scrollbar_width: 6.0,
                scrollbar_right: 6.0,
                centered_shrink_start: 1100.0,
                centered_shrink_end: 2200.0,
                centered_min_ratio: 0.58,
                centered_max_width: 1200.0,
                dialog_width: 520.0,
                dialog_padding: 20.0,
                dialog_gap: 14.0,
                dialog_radius: 18.0,
                dialog_border_width: 1.0,
                dialog_button_height: 36.0,
                dialog_button_gap: 10.0,
                dialog_button_padding_x: 14.0,
                menu_bar_height: 32.0,
                menu_bar_padding_x: 10.0,
                menu_bar_padding_y: 4.0,
                menu_bar_gap: 2.0,
                menu_bar_button_width: 48.0,
                menu_bar_button_height: 24.0,
                menu_bar_button_padding_x: 8.0,
                menu_bar_button_radius: 5.0,
                menu_text_size: 12.0,
                menu_panel_top: 30.0,
                menu_panel_width: 180.0,
                menu_panel_padding: 4.0,
                menu_panel_gap: 1.0,
                menu_panel_radius: 10.0,
                menu_item_height: 28.0,
                menu_item_padding_x: 8.0,
                menu_item_radius: 7.0,
                menu_separator_margin_x: 6.0,
                menu_separator_margin_y: 3.0,
                menu_separator_height: 1.0,
                context_menu_panel_width: 132.0,
                context_menu_submenu_width: 148.0,
                context_menu_submenu_gap: 2.0,
                context_menu_axis_panel_width: 164.0,
                table_insert_dialog_width: 380.0,
                table_insert_stepper_gap: 8.0,
                table_insert_stepper_button_size: 32.0,
                table_insert_stepper_value_min_width: 56.0,
                table_insert_stepper_value_padding_x: 10.0,
                table_insert_stepper_radius: 8.0,
                view_mode_toggle_left: 12.0,
                view_mode_toggle_bottom: 12.0,
                view_mode_toggle_padding_x: 8.0,
                view_mode_toggle_padding_y: 4.0,
                view_mode_toggle_min_width: 88.0,
                view_mode_toggle_radius: 999.0,
                view_mode_toggle_border_width: 1.0,
                view_mode_toggle_text_size: 11.0,
                status_bar_height: 24.0,
                status_bar_padding_x: 12.0,
                status_bar_item_gap: 12.0,
                status_bar_text_size: 11.0,
            },
            typography: ThemeTypography {
                text_size: 16.0,
                text_line_height: 1.6,
                h1_size: 32.0,
                h1_weight: FontWeightDef::Bold,
                h2_size: 24.0,
                h2_weight: FontWeightDef::Bold,
                h3_size: 20.0,
                h3_weight: FontWeightDef::Semibold,
                h4_size: 18.0,
                h4_weight: FontWeightDef::Semibold,
                h5_size: 16.0,
                h5_weight: FontWeightDef::Semibold,
                h6_size: 14.0,
                h6_weight: FontWeightDef::Semibold,
                code_size: 15.0,
                dialog_title_size: 20.0,
                dialog_title_weight: FontWeightDef::Semibold,
                dialog_body_size: 14.0,
                dialog_body_weight: FontWeightDef::Normal,
                dialog_button_size: 14.0,
                dialog_button_weight: FontWeightDef::Medium,
            },
            placeholders: Placeholders {
                empty_editing: String::new(),
            },
        }
    }

    /// Returns the built-in light theme.
    ///
    /// The light theme intentionally reuses the default layout and typography
    /// tokens so it can focus on palette differences.
    pub fn light_theme() -> Self {
        let base = Self::default_theme();
        Self {
            name: BUILTIN_THEME_GMARK_LIGHT_NAME.into(),
            colors: ThemeColors {
                // 浅色主题使用带轻微玉石底色的分层中性色，避免大面积纯白造成眩光。
                editor_background: Hsla::from(rgba(0xf7f8f3ff)),
                source_mode_block_bg: Hsla::from(rgba(0xf0f2ecff)),
                comment_bg: Hsla::from(rgba(0xfff4cc66)),
                text_default: Hsla::from(rgba(0x1d1d1fff)),
                text_link: Hsla::from(rgba(0x0a66c2ff)),
                text_placeholder: Hsla::from(rgba(0x6e6e73cc)),
                text_h1: Hsla::from(rgba(0x1d1d1fff)),
                text_h2: Hsla::from(rgba(0x1d1d1fff)),
                text_h3: Hsla::from(rgba(0x1d1d1fff)),
                text_h4: Hsla::from(rgba(0x1d1d1fff)),
                text_h5: Hsla::from(rgba(0x1d1d1fff)),
                text_h6: Hsla::from(rgba(0x1d1d1fff)),
                border_h1: Hsla::from(rgba(0xd4d7cfff)),
                border_h2: Hsla::from(rgba(0xe2e5ddff)),
                text_quote: Hsla::from(rgba(0x515154ff)),
                border_quote: Hsla::from(rgba(0x8e8e93ff)),
                callout_note_bg: Hsla::from(rgba(0x0a66c214)),
                callout_note_border: Hsla::from(rgba(0x0a66c2ff)),
                callout_tip_bg: Hsla::from(rgba(0x16a34a14)),
                callout_tip_border: Hsla::from(rgba(0x16a34aff)),
                callout_important_bg: Hsla::from(rgba(0x7c3aed14)),
                callout_important_border: Hsla::from(rgba(0x7c3aedff)),
                callout_warning_bg: Hsla::from(rgba(0xf9731614)),
                callout_warning_border: Hsla::from(rgba(0xf97316ff)),
                callout_caution_bg: Hsla::from(rgba(0xdc262614)),
                callout_caution_border: Hsla::from(rgba(0xdc2626ff)),
                footnote_bg: Hsla::from(rgba(0xf2f4eeff)),
                footnote_border: Hsla::from(rgba(0xd4d7cfff)),
                footnote_badge_bg: Hsla::from(rgba(0xe8ebe3ff)),
                footnote_badge_text: Hsla::from(rgba(0x515154ff)),
                footnote_backref: Hsla::from(rgba(0x0a66c2ff)),
                task_checkbox_border: Hsla::from(rgba(0x8e8e93ff)),
                task_checkbox_bg: Hsla::from(rgba(0xf7f8f3ff)),
                task_checkbox_checked_bg: Hsla::from(rgba(0x0a66c2ff)),
                task_checkbox_check: Hsla::from(rgba(0xffffffff)),
                separator_color: Hsla::from(rgba(0xd4d7cfff)),
                code_bg: Hsla::from(rgba(0xf0f2ecff)),
                code_text: Hsla::from(rgba(0x1d1d1fff)),
                code_language_input_bg: Hsla::from(rgba(0xf7f8f3ff)),
                code_language_input_border: Hsla::from(rgba(0xd4d7cfff)),
                code_language_input_text: Hsla::from(rgba(0x1d1d1fff)),
                code_language_input_placeholder: Hsla::from(rgba(0x6e6e73cc)),
                code_syntax_comment: Hsla::from(rgba(0x6b7280ff)),
                code_syntax_keyword: Hsla::from(rgba(0x7c3aedff)),
                code_syntax_string: Hsla::from(rgba(0x15803dff)),
                code_syntax_number: Hsla::from(rgba(0xc2410cff)),
                code_syntax_type: Hsla::from(rgba(0x0f766eff)),
                code_syntax_function: Hsla::from(rgba(0x0a66c2ff)),
                code_syntax_constant: Hsla::from(rgba(0xb45309ff)),
                code_syntax_variable: Hsla::from(rgba(0x1d1d1fff)),
                code_syntax_property: Hsla::from(rgba(0x0891b2ff)),
                code_syntax_operator: Hsla::from(rgba(0x9333eaff)),
                code_syntax_punctuation: Hsla::from(rgba(0x6e6e73ff)),
                table_border: Hsla::from(rgba(0xd4d7cfff)),
                table_header_bg: Hsla::from(rgba(0xf0f2ecff)),
                table_cell_bg: Hsla::from(rgba(0xf7f8f3ff)),
                table_cell_active_outline: Hsla::from(rgba(0x0a66c2ff)),
                table_axis_preview_bg: Hsla::from(rgba(0x0a66c214)),
                table_axis_selected_bg: Hsla::from(rgba(0x0a66c229)),
                table_append_button_bg: Hsla::from(rgba(0xecefe8ff)),
                table_append_button_hover: Hsla::from(rgba(0xe3e7deff)),
                table_append_button_text: Hsla::from(rgba(0x49494fff)),
                image_placeholder_bg: Hsla::from(rgba(0xf2f4eeff)),
                image_placeholder_border: Hsla::from(rgba(0xd4d7cfff)),
                image_placeholder_text: Hsla::from(rgba(0x515154ff)),
                image_caption_text: Hsla::from(rgba(0x6e6e73ff)),
                scrollbar_thumb: Hsla::from(rgba(0x8e8e93b8)),
                cursor: Hsla::from(rgba(0x1d1d1fff)),
                selection: Hsla::from(rgba(0x0a66c22e)),
                dialog_backdrop: Hsla::from(rgba(0x1d1d1f66)),
                dialog_surface: Hsla::from(rgba(0xfafbf7ff)),
                dialog_border: Hsla::from(rgba(0xd4d7cfff)),
                dialog_title: Hsla::from(rgba(0x1d1d1fff)),
                dialog_body: Hsla::from(rgba(0x3a3a3cff)),
                dialog_muted: Hsla::from(rgba(0x6e6e73ff)),
                dialog_primary_button_bg: Hsla::from(rgba(0x0071e3ff)),
                dialog_primary_button_hover: Hsla::from(rgba(0x0068d1ff)),
                dialog_primary_button_text: Hsla::from(rgba(0xffffffff)),
                dialog_secondary_button_bg: Hsla::from(rgba(0xecefe8ff)),
                dialog_secondary_button_hover: Hsla::from(rgba(0xe3e7deff)),
                dialog_secondary_button_text: Hsla::from(rgba(0x1d1d1fff)),
                dialog_danger_button_bg: Hsla::from(rgba(0xdc2626ff)),
                dialog_danger_button_hover: Hsla::from(rgba(0xb91c1cff)),
                dialog_danger_button_text: Hsla::from(rgba(0xffffffff)),
                status_bar_background: Hsla::from(rgba(0xecefe8ff)),
                status_bar_text: Hsla::from(rgba(0x49494fff)),
                status_bar_text_dim: Hsla::from(rgba(0x77777eff)),
                status_bar_button_hover: Hsla::from(rgba(0xe3e7deff)),
                chrome_background: Hsla::from(rgba(0xf1f3edff)),
                chrome_hover: Hsla::from(rgba(0xe5e8e1ff)),
                sidebar_background: Hsla::from(rgba(0xf3f5efff)),
                tab_strip_background: Hsla::from(rgba(0xecefe8ff)),
                tab_active_background: Hsla::from(rgba(0xf7f8f3ff)),
            },
            dimensions: base.dimensions,
            typography: base.typography,
            placeholders: base.placeholders,
        }
    }

    /// Parses a theme from JSON text.
    #[cfg(test)]
    pub fn from_json(json: &str) -> anyhow::Result<Self> {
        Ok(serde_json::from_str(json)?)
    }

    /// Serializes the theme into pretty-printed JSON.
    #[cfg(test)]
    pub fn to_json(&self) -> anyhow::Result<String> {
        Ok(serde_json::to_string_pretty(self)?)
    }
}
