// @author kongweiguang

//! Stable default shortcut definitions.

use super::super::*;

pub(super) const DEFINITIONS: &[ShortcutDefinition] = &[
    ShortcutDefinition {
        command: ShortcutCommand::Newline,
        id: "newline",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::shared(&["enter"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::DeleteBack,
        id: "delete_back",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::shared(&["backspace"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::Delete,
        id: "delete",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::shared(&["delete"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::WordDeleteBack,
        id: "word_delete_back",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-backspace"], &["alt-backspace"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::WordDeleteForward,
        id: "word_delete_forward",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-delete"], &["alt-delete"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FocusPrev,
        id: "focus_prev",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["up"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FocusNext,
        id: "focus_next",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["down"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveLeft,
        id: "move_left",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["left"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveRight,
        id: "move_right",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["right"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::WordMoveLeft,
        id: "word_move_left",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-left"], &["alt-left"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::WordMoveRight,
        id: "word_move_right",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-right"], &["alt-right"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::Home,
        id: "home",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["home"], &["cmd-left"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::End,
        id: "end",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["end"], &["cmd-right"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveToDocumentStart,
        id: "move_to_document_start",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-home"], &["cmd-up"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveToDocumentEnd,
        id: "move_to_document_end",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-end"], &["cmd-down"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::BlockUp,
        id: "block_up",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-up"], &["alt-up"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::BlockDown,
        id: "block_down",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-down"], &["alt-down"]),
        context: BLOCK_CONTEXT,
    },
    // Page scroll and document jumps operate on the editor viewport rather than
    // a single block, so they use global bindings (no context) and stay active
    // in both Rendered and Source mode.
    ShortcutDefinition {
        command: ShortcutCommand::PageUp,
        id: "page_up",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["pageup"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::PageDown,
        id: "page_down",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["pagedown"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::JumpToTop,
        id: "jump_to_top",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::JumpToBottom,
        id: "jump_to_bottom",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectLeft,
        id: "select_left",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["shift-left"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectRight,
        id: "select_right",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["shift-right"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectUp,
        id: "select_up",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["shift-up"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectDown,
        id: "select_down",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["shift-down"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectPageUp,
        id: "select_page_up",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["shift-pageup"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectPageDown,
        id: "select_page_down",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["shift-pagedown"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::WordSelectLeft,
        id: "word_select_left",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-left"], &["alt-shift-left"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::WordSelectRight,
        id: "word_select_right",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-right"], &["alt-shift-right"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectHome,
        id: "select_home",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["shift-home"], &["cmd-shift-left"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectEnd,
        id: "select_end",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["shift-end"], &["cmd-shift-right"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectToDocumentStart,
        id: "select_to_document_start",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-home"], &["cmd-shift-up"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectToDocumentEnd,
        id: "select_to_document_end",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-end"], &["cmd-shift-down"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SelectAll,
        id: SELECT_ALL_ID,
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-a"], &["cmd-a"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::DuplicateLine,
        id: "duplicate_line",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-d"], &["cmd-d"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::DeleteLine,
        id: "delete_line",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-y"], &["cmd-y"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveLineUp,
        id: "move_line_up",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::shared(&["alt-shift-up"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveLineDown,
        id: "move_line_down",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::shared(&["alt-shift-down"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::Copy,
        id: "copy",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-c"], &["cmd-c"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CopyAsMarkdown,
        id: "copy_as_markdown",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-c"], &["cmd-shift-c"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::Cut,
        id: "cut",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-x"], &["cmd-x"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::Paste,
        id: "paste",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-v"], &["cmd-v"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::PasteAsPlainText,
        id: "paste_as_plain_text",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-alt-shift-v"], &["cmd-alt-shift-v"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::Undo,
        id: "undo",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-z"], &["cmd-z"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::Redo,
        id: "redo",
        category: ShortcutCategory::Edit,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-z"], &["cmd-shift-z"]),
        context: BLOCK_CONTEXT,
    },
];
