// @author kongweiguang

//! Stable default shortcut definitions.

use super::super::*;

pub(super) const DEFINITIONS: &[ShortcutDefinition] = &[
    ShortcutDefinition {
        command: ShortcutCommand::BoldSelection,
        id: "bold_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::platform(&["ctrl-b"], &["cmd-b"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ItalicSelection,
        id: "italic_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::platform(&["ctrl-i"], &["cmd-i"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::StrikethroughSelection,
        id: "strikethrough_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::platform(&["alt-shift-5"], &["cmd-shift-x"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::UnderlineSelection,
        id: "underline_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::platform(&["ctrl-u"], &["cmd-u"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CodeSelection,
        id: "code_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-`"], &["cmd-shift-`"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::LinkSelection,
        id: "link_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::platform(&["ctrl-k"], &["cmd-k"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::HighlightSelection,
        id: "highlight_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::shared(&[]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SuperscriptSelection,
        id: "superscript_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::shared(&[]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SubscriptSelection,
        id: "subscript_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::shared(&[]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::InlineMathSelection,
        id: "inline_math_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::shared(&[]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SetParagraph,
        id: "set_paragraph",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-0"], &["cmd-0"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SetHeading1,
        id: "set_heading_1",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-1"], &["cmd-1"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SetHeading2,
        id: "set_heading_2",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-2"], &["cmd-2"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SetHeading3,
        id: "set_heading_3",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-3"], &["cmd-3"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SetHeading4,
        id: "set_heading_4",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-4"], &["cmd-4"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SetHeading5,
        id: "set_heading_5",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-5"], &["cmd-5"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SetHeading6,
        id: "set_heading_6",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-6"], &["cmd-6"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::IndentBlock,
        id: "indent_block",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::shared(&["tab"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::OutdentBlock,
        id: "outdent_block",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::shared(&["shift-tab"]),
        context: BLOCK_CONTEXT,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ExitCodeBlock,
        id: "exit_code_block",
        category: ShortcutCategory::Block,
        default_keys: ShortcutDefaults::platform(&["ctrl-enter"], &["cmd-enter"]),
        context: BLOCK_CONTEXT,
    },
];
