// @author kongweiguang

//! Stable default shortcut definitions.

use super::super::*;

pub(super) const DEFINITIONS: &[ShortcutDefinition] = &[
    ShortcutDefinition {
        command: ShortcutCommand::SaveDocument,
        id: "save_document",
        category: ShortcutCategory::File,
        default_keys: &["cmd-s", "ctrl-s"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SaveDocumentAs,
        id: "save_document_as",
        category: ShortcutCategory::File,
        default_keys: &["cmd-shift-s", "ctrl-shift-s"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CollapseFold,
        id: "collapse_fold",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-alt-[", "ctrl-alt-["],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ExpandFold,
        id: "expand_fold",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-alt-]", "ctrl-alt-]"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CollapseAllFolds,
        id: "collapse_all_folds",
        category: ShortcutCategory::Navigation,
        default_keys: &[],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ExpandAllFolds,
        id: "expand_all_folds",
        category: ShortcutCategory::Navigation,
        default_keys: &[],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FormatDocument,
        id: "format_document",
        category: ShortcutCategory::Formatting,
        default_keys: &["shift-alt-f"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FormatSelection,
        id: "format_selection",
        category: ShortcutCategory::Formatting,
        default_keys: &[],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CancelFormatting,
        id: "cancel_formatting",
        category: ShortcutCategory::Formatting,
        default_keys: &[],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::NewTab,
        id: "new_tab",
        category: ShortcutCategory::File,
        default_keys: &["cmd-n", "ctrl-n", "cmd-t", "ctrl-t"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::NewWindow,
        id: "new_window",
        category: ShortcutCategory::File,
        default_keys: &["cmd-shift-n", "ctrl-shift-n"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::OpenFile,
        id: "open_file",
        category: ShortcutCategory::File,
        default_keys: &["cmd-o", "ctrl-o"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::QuitApplication,
        id: "quit_application",
        category: ShortcutCategory::File,
        default_keys: QUIT_APPLICATION_DEFAULT_KEYS,
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CloseWindow,
        id: "close_window",
        category: ShortcutCategory::File,
        default_keys: CLOSE_WINDOW_DEFAULT_KEYS,
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CloseTab,
        id: "close_tab",
        category: ShortcutCategory::File,
        default_keys: &["cmd-w", "ctrl-w"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ReopenClosedTab,
        id: "reopen_closed_tab",
        category: ShortcutCategory::File,
        default_keys: &["cmd-shift-t", "ctrl-shift-t"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::PreviousTab,
        id: "previous_tab",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-pageup", "ctrl-pageup"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::NextTab,
        id: "next_tab",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-pagedown", "ctrl-pagedown"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::DismissTransientUi,
        id: "dismiss_transient_ui",
        category: ShortcutCategory::Other,
        default_keys: &["escape"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleViewMode,
        id: "toggle_view_mode",
        category: ShortcutCategory::Navigation,
        default_keys: &["ctrl-tab", "cmd-tab"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleWorkspace,
        id: "toggle_workspace",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-b", "ctrl-b"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleDocumentSidebar,
        id: "toggle_document_sidebar",
        category: ShortcutCategory::Navigation,
        default_keys: &[],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::OpenFolder,
        id: "open_folder",
        category: ShortcutCategory::File,
        default_keys: &["cmd-shift-o", "ctrl-shift-o"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::OpenPreferences,
        id: "open_preferences",
        category: ShortcutCategory::File,
        default_keys: &["cmd-,", "ctrl-,"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::QuickOpen,
        id: "quick_open",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-p", "ctrl-p"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CommandPalette,
        id: "command_palette",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-shift-p", "ctrl-shift-p"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::GoToLine,
        id: "go_to_line",
        category: ShortcutCategory::Navigation,
        default_keys: &["ctrl-g"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FindInDocument,
        id: "find_in_document",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-f", "ctrl-f"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ReplaceInDocument,
        id: "replace_in_document",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-alt-f", "ctrl-h"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FindNext,
        id: "find_next",
        category: ShortcutCategory::Navigation,
        default_keys: &["f3", "cmd-g"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FindPrevious,
        id: "find_previous",
        category: ShortcutCategory::Navigation,
        default_keys: &["shift-f3", "cmd-shift-g"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleFocusMode,
        id: "toggle_focus_mode",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-shift-f", "ctrl-shift-f"],
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleTypewriterMode,
        id: "toggle_typewriter_mode",
        category: ShortcutCategory::Navigation,
        default_keys: &["cmd-alt-t", "ctrl-alt-t"],
        context: None,
    },
];
