// @author kongweiguang

//! Stable default shortcut definitions.

use super::super::*;

pub(super) const DEFINITIONS: &[ShortcutDefinition] = &[
    ShortcutDefinition {
        command: ShortcutCommand::SaveDocument,
        id: "save_document",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-s"], &["cmd-s"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SaveDocumentAs,
        id: "save_document_as",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-s"], &["cmd-shift-s"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CollapseFold,
        id: "collapse_fold",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-["], &["cmd-alt-["]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ExpandFold,
        id: "expand_fold",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-]"], &["cmd-alt-]"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CollapseAllFolds,
        id: "collapse_all_folds",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ExpandAllFolds,
        id: "expand_all_folds",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FormatDocument,
        id: "format_document",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::platform(&["ctrl-alt-l"], &["cmd-alt-l"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FormatSelection,
        id: "format_selection",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CancelFormatting,
        id: "cancel_formatting",
        category: ShortcutCategory::Formatting,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::NewTab,
        id: "new_tab",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-n", "ctrl-t"], &["cmd-n", "cmd-t"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::NewWindow,
        id: "new_window",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-n"], &["cmd-shift-n"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::OpenFile,
        id: "open_file",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-o"], &["cmd-o"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::QuitApplication,
        id: "quit_application",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&[], &["cmd-q"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CloseWindow,
        id: "close_window",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-w"], &["cmd-shift-w"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CloseTab,
        id: "close_tab",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-w"], &["cmd-w"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ReopenClosedTab,
        id: "reopen_closed_tab",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-t"], &["cmd-shift-t"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::PreviousTab,
        id: "previous_tab",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["alt-left"], &["cmd-shift-["]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::NextTab,
        id: "next_tab",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["alt-right"], &["cmd-shift-]"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::DismissTransientUi,
        id: "dismiss_transient_ui",
        category: ShortcutCategory::Other,
        default_keys: ShortcutDefaults::shared(&["escape"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleViewMode,
        id: "toggle_view_mode",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-/"], &["cmd-/"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleWorkspace,
        id: "toggle_workspace",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["alt-1"], &["cmd-1"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleDocumentSidebar,
        id: "toggle_document_sidebar",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SplitRight,
        id: "split_right",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::SplitDown,
        id: "split_down",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ClosePane,
        id: "close_pane",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FocusPaneLeft,
        id: "focus_pane_left",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FocusPaneRight,
        id: "focus_pane_right",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FocusPaneUp,
        id: "focus_pane_up",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FocusPaneDown,
        id: "focus_pane_down",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveTabToPaneLeft,
        id: "move_tab_to_pane_left",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveTabToPaneRight,
        id: "move_tab_to_pane_right",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveTabToPaneUp,
        id: "move_tab_to_pane_up",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::MoveTabToPaneDown,
        id: "move_tab_to_pane_down",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::BalancePanes,
        id: "balance_panes",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&[]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::OpenFolder,
        id: "open_folder",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-o"], &["cmd-shift-o"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::OpenPreferences,
        id: "open_preferences",
        category: ShortcutCategory::File,
        default_keys: ShortcutDefaults::platform(&["ctrl-alt-s"], &["cmd-,"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::QuickOpen,
        id: "quick_open",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-p"], &["cmd-p"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::CommandPalette,
        id: "command_palette",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-shift-a"], &["cmd-shift-a"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::GoToLine,
        id: "go_to_line",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-g"], &["cmd-l"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FindInDocument,
        id: "find_in_document",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-f"], &["cmd-f"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ReplaceInDocument,
        id: "replace_in_document",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["ctrl-r"], &["cmd-r"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FindNext,
        id: "find_next",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["f3"], &["cmd-g"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::FindPrevious,
        id: "find_previous",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::platform(&["shift-f3"], &["cmd-shift-g"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleFocusMode,
        id: "toggle_focus_mode",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["f8"]),
        context: None,
    },
    ShortcutDefinition {
        command: ShortcutCommand::ToggleTypewriterMode,
        id: "toggle_typewriter_mode",
        category: ShortcutCategory::Navigation,
        default_keys: ShortcutDefaults::shared(&["f9"]),
        context: None,
    },
];
