// @author kongweiguang

//! Built-in palette constructors.

use super::*;

impl Theme {
    /// Returns the default Xcode dark palette.
    pub fn xcode_dark() -> Self {
        Self {
            name: "Xcode Dark".into(),
            colors: ThemeColors {
                // Xcode 27 官方产品图中源码编辑器、导航区和工具区使用稳定实色分层。
                editor_background: Hsla::from(rgba(0x292a30ff)),
                source_mode_block_bg: Hsla::from(rgba(0x21222eff)),
                comment_bg: Hsla::from(rgba(0x7f8c9830)),
                text_default: Hsla::from(rgba(0xffffffff)),
                text_link: Hsla::from(rgba(0x0a84ffff)),
                text_placeholder: Hsla::from(rgba(0x8f8f98cc)),
                text_h1: Hsla::from(rgba(0xffffffff)),
                text_h2: Hsla::from(rgba(0xffffffff)),
                text_h3: Hsla::from(rgba(0xffffffff)),
                text_h4: Hsla::from(rgba(0xffffffff)),
                text_h5: Hsla::from(rgba(0xffffffff)),
                text_h6: Hsla::from(rgba(0xffffffff)),
                border_h1: Hsla::from(rgba(0x5b5c66ff)),
                border_h2: Hsla::from(rgba(0x5b5c66cc)),
                text_quote: Hsla::from(rgba(0xc8c8d0ff)),
                border_quote: Hsla::from(rgba(0x7d7e87ff)),
                callout_note_bg: Hsla::from(rgba(0x94a3b81f)),
                callout_note_border: Hsla::from(rgba(0x94a3b4ff)),
                callout_tip_bg: Hsla::from(rgba(0x1d4ed81f)),
                callout_tip_border: Hsla::from(rgba(0x60a5faff)),
                callout_important_bg: Hsla::from(rgba(0xa78bfa1f)),
                callout_important_border: Hsla::from(rgba(0xa78bfaff)),
                callout_warning_bg: Hsla::from(rgba(0xfb71851f)),
                callout_warning_border: Hsla::from(rgba(0xfb7185ff)),
                callout_caution_bg: Hsla::from(rgba(0xdc26261f)),
                callout_caution_border: Hsla::from(rgba(0xf87171ff)),
                footnote_bg: Hsla::from(rgba(0x21222eff)),
                footnote_border: Hsla::from(rgba(0x7d7e8752)),
                footnote_badge_bg: Hsla::from(rgba(0xc8c8d024)),
                footnote_badge_text: Hsla::from(rgba(0xc8c8d0cc)),
                footnote_backref: Hsla::from(rgba(0x8f8f98ff)),
                task_checkbox_border: Hsla::from(rgba(0x7d7e87ff)),
                task_checkbox_bg: Hsla::from(rgba(0x00000000)),
                task_checkbox_checked_bg: Hsla::from(rgba(0x0a84ffff)),
                task_checkbox_check: Hsla::from(rgba(0xffffffff)),
                separator_color: Hsla::from(rgba(0x7d7e87ff)),
                code_bg: Hsla::from(rgba(0x21222eff)),
                code_text: Hsla::from(rgba(0xffffffff)),
                code_language_input_bg: Hsla::from(rgba(0x21222eff)),
                code_language_input_border: Hsla::from(rgba(0x5b5c66cc)),
                code_language_input_text: Hsla::from(rgba(0xffffffff)),
                code_language_input_placeholder: Hsla::from(rgba(0x8f8f98cc)),
                code_syntax_comment: Hsla::from(rgba(0x7f8c98ff)),
                code_syntax_keyword: Hsla::from(rgba(0xff7ab2ff)),
                code_syntax_string: Hsla::from(rgba(0xfc6a5dff)),
                code_syntax_number: Hsla::from(rgba(0xd0bf69ff)),
                code_syntax_type: Hsla::from(rgba(0x5dd8ffff)),
                code_syntax_function: Hsla::from(rgba(0x67b7a4ff)),
                code_syntax_constant: Hsla::from(rgba(0xa8a8ffff)),
                code_syntax_variable: Hsla::from(rgba(0xffffffff)),
                code_syntax_property: Hsla::from(rgba(0x9cdcfeff)),
                code_syntax_operator: Hsla::from(rgba(0xff7ab2ff)),
                code_syntax_punctuation: Hsla::from(rgba(0xc8c8d0ff)),
                table_border: Hsla::from(rgba(0x484950ff)),
                table_header_bg: Hsla::from(rgba(0x21222eff)),
                table_cell_bg: Hsla::from(rgba(0x292a30ff)),
                table_cell_active_outline: Hsla::from(rgba(0x0a84ffff)),
                table_axis_preview_bg: Hsla::from(rgba(0x0a84ff2e)),
                table_axis_selected_bg: Hsla::from(rgba(0x0a84ff55)),
                table_append_button_bg: Hsla::from(rgba(0x303139ff)),
                table_append_button_hover: Hsla::from(rgba(0x3b3c46ff)),
                table_append_button_text: Hsla::from(rgba(0xffffffff)),
                image_placeholder_bg: Hsla::from(rgba(0x21222eff)),
                image_placeholder_border: Hsla::from(rgba(0x5b5c66ff)),
                image_placeholder_text: Hsla::from(rgba(0xc8c8d0ff)),
                image_caption_text: Hsla::from(rgba(0x8f8f98ff)),
                scrollbar_thumb: Hsla::from(rgba(0xc8c8d0b8)),
                cursor: Hsla::from(rgba(0xffffffff)),
                selection: Hsla::from(rgba(0x0a84ff4d)),
                dialog_backdrop: Hsla::from(rgba(0x000000b8)),
                dialog_surface: Hsla::from(rgba(0x292a30ff)),
                dialog_border: Hsla::from(rgba(0x484950ff)),
                dialog_title: Hsla::from(rgba(0xffffffff)),
                dialog_body: Hsla::from(rgba(0xd1d1d6ff)),
                dialog_muted: Hsla::from(rgba(0x8f8f98ff)),
                dialog_primary_button_bg: Hsla::from(rgba(0x0a84ffff)),
                dialog_primary_button_hover: Hsla::from(rgba(0x0077e6ff)),
                dialog_primary_button_text: Hsla::from(rgba(0xffffffff)),
                dialog_secondary_button_bg: Hsla::from(rgba(0x3a3b43ff)),
                dialog_secondary_button_hover: Hsla::from(rgba(0x484950ff)),
                dialog_secondary_button_text: Hsla::from(rgba(0xffffffff)),
                // Doubles as the destructive menu-item text color (e.g. Delete
                // Row/Column), so it must stay legible on the dark menu surface
                // rather than the muted red used previously.
                dialog_danger_button_bg: Hsla::from(rgba(0xef4444ff)),
                dialog_danger_button_hover: Hsla::from(rgba(0xdc2626ff)),
                dialog_danger_button_text: Hsla::from(rgba(0xfef2f2ff)),
                status_bar_background: Hsla::from(rgba(0x21222eff)),
                status_bar_text: Hsla::from(rgba(0xd1d1d6cc)),
                status_bar_text_dim: Hsla::from(rgba(0x8f8f98ff)),
                status_bar_button_hover: Hsla::from(rgba(0x3b3c46ff)),
                chrome_background: Hsla::from(rgba(0x1c1d2aff)),
                chrome_hover: Hsla::from(rgba(0x292a30ff)),
                sidebar_background: Hsla::from(rgba(0x1c1d2aff)),
                tab_strip_background: Hsla::from(rgba(0x21222eff)),
                tab_active_background: Hsla::from(rgba(0x292a30ff)),
            },
            dimensions: ThemeDimensions {
                editor_padding: 24.0,
                block_gap: 6.0,
                block_min_height: 28.0,
                block_padding_y: 4.0,
                block_padding_x: 12.0,
                nested_block_indent: 20.0,
                list_marker_gap: 8.0,
                list_marker_width: 12.0,
                ordered_list_marker_width: 20.0,
                task_checkbox_size: 14.0,
                task_checkbox_radius: 4.0,
                task_checkbox_border_width: 1.0,
                task_checkbox_check_size: 10.0,
                h1_padding_bottom: 4.0,
                h1_margin_bottom: 4.0,
                cursor_width: 2.0,
                underline_thickness: 1.0,
                h1_border_width: 1.0,
                quote_border_width: 3.0,
                quote_padding_left: 12.0,
                callout_padding_x: 14.0,
                callout_padding_y: 10.0,
                callout_body_gap: 8.0,
                callout_radius: 10.0,
                callout_border_width: 4.0,
                callout_header_gap: 6.0,
                callout_header_margin_bottom: 6.0,
                footnote_padding_x: 10.0,
                footnote_padding_y: 6.0,
                footnote_radius: 6.0,
                footnote_badge_padding_x: 4.0,
                footnote_badge_padding_y: 1.0,
                separator_thickness: 1.0,
                separator_inset_x: 40.0,
                separator_margin_y: 10.0,
                code_block_padding_y: 8.0,
                code_block_padding_x: 12.0,
                code_bg_pad_x: 3.0,
                code_bg_pad_y: 1.0,
                code_bg_radius: 4.0,
                code_language_input_width: 156.0,
                code_language_input_height: 18.0,
                code_language_input_padding_x: 8.0,
                code_language_input_padding_y: 3.0,
                code_language_input_radius: 6.0,
                code_language_input_border_width: 1.0,
                code_language_input_gap: 8.0,
                table_cell_padding_x: 10.0,
                table_cell_padding_y: 8.0,
                table_cell_min_height: 42.0,
                table_append_button_extent: 16.0,
                table_append_button_inset: 8.0,
                table_append_activation_band: 18.0,
                image_radius: 12.0,
                image_root_max_height: 420.0,
                image_cell_max_height: 180.0,
                image_root_placeholder_height: 260.0,
                image_cell_placeholder_height: 120.0,
                image_caption_gap: 8.0,
                scrollbar_width: 6.0,
                scrollbar_right: 6.0,
                centered_shrink_start: 1100.0,
                centered_shrink_end: 2200.0,
                centered_min_ratio: 0.58,
                centered_max_width: 1200.0,
                dialog_width: 520.0,
                dialog_padding: 20.0,
                dialog_gap: 14.0,
                dialog_radius: 18.0,
                dialog_border_width: 1.0,
                dialog_button_height: 36.0,
                dialog_button_gap: 10.0,
                dialog_button_padding_x: 14.0,
                menu_bar_height: 32.0,
                menu_bar_padding_x: 10.0,
                menu_bar_padding_y: 4.0,
                menu_bar_gap: 2.0,
                menu_bar_button_width: 48.0,
                menu_bar_button_height: 24.0,
                menu_bar_button_padding_x: 8.0,
                menu_bar_button_radius: 5.0,
                menu_text_size: 12.0,
                menu_panel_top: 30.0,
                menu_panel_width: 180.0,
                menu_panel_padding: 4.0,
                menu_panel_gap: 1.0,
                menu_panel_radius: 10.0,
                menu_item_height: 28.0,
                menu_item_padding_x: 8.0,
                menu_item_radius: 7.0,
                menu_separator_margin_x: 6.0,
                menu_separator_margin_y: 3.0,
                menu_separator_height: 1.0,
                context_menu_panel_width: 132.0,
                context_menu_submenu_width: 148.0,
                context_menu_submenu_gap: 2.0,
                context_menu_axis_panel_width: 164.0,
                table_insert_dialog_width: 380.0,
                table_insert_stepper_gap: 8.0,
                table_insert_stepper_button_size: 32.0,
                table_insert_stepper_value_min_width: 56.0,
                table_insert_stepper_value_padding_x: 10.0,
                table_insert_stepper_radius: 8.0,
                view_mode_toggle_left: 12.0,
                view_mode_toggle_bottom: 12.0,
                view_mode_toggle_padding_x: 8.0,
                view_mode_toggle_padding_y: 4.0,
                view_mode_toggle_min_width: 88.0,
                view_mode_toggle_radius: 999.0,
                view_mode_toggle_border_width: 1.0,
                view_mode_toggle_text_size: 11.0,
                status_bar_height: 24.0,
                status_bar_padding_x: 12.0,
                status_bar_item_gap: 12.0,
                status_bar_text_size: 11.0,
            },
            typography: ThemeTypography {
                text_size: 16.0,
                text_line_height: 1.6,
                h1_size: 32.0,
                h1_weight: FontWeightDef::Bold,
                h2_size: 24.0,
                h2_weight: FontWeightDef::Bold,
                h3_size: 20.0,
                h3_weight: FontWeightDef::Semibold,
                h4_size: 18.0,
                h4_weight: FontWeightDef::Semibold,
                h5_size: 16.0,
                h5_weight: FontWeightDef::Semibold,
                h6_size: 14.0,
                h6_weight: FontWeightDef::Semibold,
                code_size: 15.0,
                dialog_title_size: 20.0,
                dialog_title_weight: FontWeightDef::Semibold,
                dialog_body_size: 14.0,
                dialog_body_weight: FontWeightDef::Normal,
                dialog_button_size: 14.0,
                dialog_button_weight: FontWeightDef::Medium,
            },
            placeholders: Placeholders {
                empty_editing: String::new(),
            },
        }
    }

    /// Returns the default Xcode light palette.
    ///
    /// The light theme intentionally reuses the default layout and typography
    /// tokens so it can focus on palette differences.
    pub fn xcode_light() -> Self {
        let base = Self::xcode_dark();
        Self {
            name: "Xcode Light".into(),
            colors: ThemeColors {
                editor_background: Hsla::from(rgba(0xffffffff)),
                source_mode_block_bg: Hsla::from(rgba(0xf5f5f5ff)),
                comment_bg: Hsla::from(rgba(0xfff4cc66)),
                text_default: Hsla::from(rgba(0x000000ff)),
                text_link: Hsla::from(rgba(0x007affff)),
                text_placeholder: Hsla::from(rgba(0x6e6e73cc)),
                text_h1: Hsla::from(rgba(0x000000ff)),
                text_h2: Hsla::from(rgba(0x000000ff)),
                text_h3: Hsla::from(rgba(0x000000ff)),
                text_h4: Hsla::from(rgba(0x000000ff)),
                text_h5: Hsla::from(rgba(0x000000ff)),
                text_h6: Hsla::from(rgba(0x000000ff)),
                border_h1: Hsla::from(rgba(0xd1d1d6ff)),
                border_h2: Hsla::from(rgba(0xe5e5eaff)),
                text_quote: Hsla::from(rgba(0x515154ff)),
                border_quote: Hsla::from(rgba(0x8e8e93ff)),
                callout_note_bg: Hsla::from(rgba(0x007aff14)),
                callout_note_border: Hsla::from(rgba(0x007affff)),
                callout_tip_bg: Hsla::from(rgba(0x16a34a14)),
                callout_tip_border: Hsla::from(rgba(0x16a34aff)),
                callout_important_bg: Hsla::from(rgba(0x7c3aed14)),
                callout_important_border: Hsla::from(rgba(0x7c3aedff)),
                callout_warning_bg: Hsla::from(rgba(0xf9731614)),
                callout_warning_border: Hsla::from(rgba(0xf97316ff)),
                callout_caution_bg: Hsla::from(rgba(0xdc262614)),
                callout_caution_border: Hsla::from(rgba(0xdc2626ff)),
                footnote_bg: Hsla::from(rgba(0xf5f5f5ff)),
                footnote_border: Hsla::from(rgba(0xd1d1d6ff)),
                footnote_badge_bg: Hsla::from(rgba(0xe5e5eaff)),
                footnote_badge_text: Hsla::from(rgba(0x515154ff)),
                footnote_backref: Hsla::from(rgba(0x007affff)),
                task_checkbox_border: Hsla::from(rgba(0x8e8e93ff)),
                task_checkbox_bg: Hsla::from(rgba(0xffffffff)),
                task_checkbox_checked_bg: Hsla::from(rgba(0x007affff)),
                task_checkbox_check: Hsla::from(rgba(0xffffffff)),
                separator_color: Hsla::from(rgba(0xd1d1d6ff)),
                code_bg: Hsla::from(rgba(0xf5f5f5ff)),
                code_text: Hsla::from(rgba(0x000000ff)),
                code_language_input_bg: Hsla::from(rgba(0xffffffff)),
                code_language_input_border: Hsla::from(rgba(0xd1d1d6ff)),
                code_language_input_text: Hsla::from(rgba(0x000000ff)),
                code_language_input_placeholder: Hsla::from(rgba(0x6e6e73cc)),
                code_syntax_comment: Hsla::from(rgba(0x5d6c79ff)),
                code_syntax_keyword: Hsla::from(rgba(0xad3da4ff)),
                code_syntax_string: Hsla::from(rgba(0xd12f1bff)),
                code_syntax_number: Hsla::from(rgba(0x272ad8ff)),
                code_syntax_type: Hsla::from(rgba(0x0b4f79ff)),
                code_syntax_function: Hsla::from(rgba(0x326d74ff)),
                code_syntax_constant: Hsla::from(rgba(0x703daaff)),
                code_syntax_variable: Hsla::from(rgba(0x000000ff)),
                code_syntax_property: Hsla::from(rgba(0x0b4f79ff)),
                code_syntax_operator: Hsla::from(rgba(0xad3da4ff)),
                code_syntax_punctuation: Hsla::from(rgba(0x4a4a4fff)),
                table_border: Hsla::from(rgba(0xd1d1d6ff)),
                table_header_bg: Hsla::from(rgba(0xf5f5f5ff)),
                table_cell_bg: Hsla::from(rgba(0xffffffff)),
                table_cell_active_outline: Hsla::from(rgba(0x007affff)),
                table_axis_preview_bg: Hsla::from(rgba(0x007aff1f)),
                table_axis_selected_bg: Hsla::from(rgba(0x007aff3d)),
                table_append_button_bg: Hsla::from(rgba(0xf2f2f7ff)),
                table_append_button_hover: Hsla::from(rgba(0xe5e5eaff)),
                table_append_button_text: Hsla::from(rgba(0x49494fff)),
                image_placeholder_bg: Hsla::from(rgba(0xf5f5f5ff)),
                image_placeholder_border: Hsla::from(rgba(0xd1d1d6ff)),
                image_placeholder_text: Hsla::from(rgba(0x515154ff)),
                image_caption_text: Hsla::from(rgba(0x6e6e73ff)),
                scrollbar_thumb: Hsla::from(rgba(0x8e8e93b8)),
                cursor: Hsla::from(rgba(0x000000ff)),
                selection: Hsla::from(rgba(0x007aff2e)),
                dialog_backdrop: Hsla::from(rgba(0x1d1d1f66)),
                dialog_surface: Hsla::from(rgba(0xffffffff)),
                dialog_border: Hsla::from(rgba(0xd1d1d6ff)),
                dialog_title: Hsla::from(rgba(0x000000ff)),
                dialog_body: Hsla::from(rgba(0x3a3a3cff)),
                dialog_muted: Hsla::from(rgba(0x6e6e73ff)),
                dialog_primary_button_bg: Hsla::from(rgba(0x007affff)),
                dialog_primary_button_hover: Hsla::from(rgba(0x006ee6ff)),
                dialog_primary_button_text: Hsla::from(rgba(0xffffffff)),
                dialog_secondary_button_bg: Hsla::from(rgba(0xf2f2f7ff)),
                dialog_secondary_button_hover: Hsla::from(rgba(0xe5e5eaff)),
                dialog_secondary_button_text: Hsla::from(rgba(0x000000ff)),
                dialog_danger_button_bg: Hsla::from(rgba(0xdc2626ff)),
                dialog_danger_button_hover: Hsla::from(rgba(0xb91c1cff)),
                dialog_danger_button_text: Hsla::from(rgba(0xffffffff)),
                status_bar_background: Hsla::from(rgba(0xf5f5f5ff)),
                status_bar_text: Hsla::from(rgba(0x49494fff)),
                status_bar_text_dim: Hsla::from(rgba(0x77777eff)),
                status_bar_button_hover: Hsla::from(rgba(0xe5e5eaff)),
                chrome_background: Hsla::from(rgba(0xf5f5f5ff)),
                chrome_hover: Hsla::from(rgba(0xe5e5eaff)),
                sidebar_background: Hsla::from(rgba(0xf8fafaff)),
                tab_strip_background: Hsla::from(rgba(0xf2f2f2ff)),
                tab_active_background: Hsla::from(rgba(0xffffffff)),
            },
            dimensions: base.dimensions,
            typography: base.typography,
            placeholders: base.placeholders,
        }
    }
}
